export const categories = [
    "All",
    "Main Course",
    "Appetizer",
    "Salad",
    "Dessert",
    "Breakfast",
    "Beverage",
  ];
  
  export const cuisines = [
    "All",
    "American",
    "Chinese",
    "French",
    "Indian",
    "Italian",
    "Japanese",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Thai",
  ];
  
  export const dietaryOptions = [
    "Vegetarian",
    "Vegan",
    "Gluten-Free",
  ];
  
  export const foodData = [
    {
      id: 1,
      name: "Margherita Pizza",
      category: "Main Course",
      cuisine: "Italian",
      description: "Classic pizza with tomato sauce, mozzarella, and fresh basil.",
      price: 12.99,
      rating: 4.7,
      prepTime: 20,
      distance: 1.2,
      image: "/placeholder.svg?height=400&width=600",
      dietaryInfo: ["Vegetarian"],
    },
    {
      id: 2,
      name: "Classic Beef Burger",
      category: "Main Course",
      cuisine: "American",
      description: "Juicy beef patty with lettuce, tomato, cheese, and special sauce on brioche bun.",
      price: 10.99,
      rating: 4.5,
      prepTime: 15,
      distance: 0.8,
      image: "/placeholder.svg?height=400&width=600",
    },
    {
      id: 3,
      name: "Chicken Caesar Salad",
      category: "Salad",
      cuisine: "Italian",
      description: "Fresh romaine with grilled chicken, parmesan, croutons, and Caesar dressing.",
      price: 9.99,
      rating: 4.3,
      prepTime: 10,
      distance: 1.5,
      image: "/placeholder.svg?height=400&width=600",
    },
    {
      id: 4,
      name: "Vegetable Stir Fry",
      category: "Main Course",
      cuisine: "Chinese",
      description: "Mixed vegetables stir-fried in a savory sauce with rice or noodles.",
      price: 11.99,
      rating: 4.4,
      prepTime: 18,
      distance: 2.0,
      image: "/placeholder.svg?height=400&width=600",
      dietaryInfo: ["Vegetarian", "Vegan"],
    },
    {
      id: 5,
      name: "Chocolate Brownie",
      category: "Dessert",
      cuisine: "American",
      description: "Fudgy brownie served warm with vanilla ice cream and chocolate sauce.",
      price: 6.99,
      rating: 4.8,
      prepTime: 5,
      distance: 1.2,
      image: "/placeholder.svg?height=400&width=600",
      dietaryInfo: ["Vegetarian"],
    },
    {
      id: 6,
      name: "Pepperoni Pizza",
      category: "Main Course",
      cuisine: "Italian",
      description: "Classic pizza topped with tomato sauce, mozzarella, and spicy pepperoni.",
      price: 13.99,
      rating: 4.6,
      prepTime: 20,
      distance: 1.2,
      image: "/placeholder.svg?height=400&width=600",
    },
    // Continue adding more food items (id: 7 - 20) same way
  ];
  